# USAGE
# python Plot_Bootstrap_Results.py

##### PYTHON PACKAGES
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# --- FILE SETUP ---
INPUT_FILENAME = 'CharacterDescriptors/bootstrap_results_ensemble.pkl'

# Define the metrics we want to plot
METRICS_TO_PLOT = ['Precision', 'Recall', 'F1-Score']

# --- LOAD DATA ---
try:
    df_results = pd.read_pickle(INPUT_FILENAME)
    print(f"Successfully loaded data from {INPUT_FILENAME}.")
except FileNotFoundError:
    print(f"Error: The file '{INPUT_FILENAME}' was not found. Please ensure it has been generated by CharacterClassifier_Bootstrap.py.")
    exit()
except Exception as e:
    print(f"Error loading pickle file: {e}")
    exit()

# --- PLOTTING ---

# Determine global minimum and maximum for y-axis to ensure consistency across plots
# We use the minimum median support (30) from the summary as a reference point to start the Y-axis from 0
# However, given the high median performance (1.0 for digits), we will focus the y-axis 
# on the range of actual observed values for better differentiation.
global_min = df_results[METRICS_TO_PLOT].min().min()
global_max = df_results[METRICS_TO_PLOT].max().max()

# Set common y-axis range. If max is 1.0, set range to 0.9 to 1.0 for better differentiation 
# of the Digits dataset, but if the minimum is much lower, we'll start lower.
# Since the summary showed perfect scores for Digits, we'll try to visually separate 
# the Consonant results while acknowledging the ceiling at 1.0.
if global_min > 0.8:
    y_min = 0.8
else:
    y_min = 0.0

y_max = 1.02 # Slightly above 1.0 for ceiling clarity

# Create a figure with one row and three columns (one for each metric)
fig, axes = plt.subplots(1, 3, figsize=(18, 6), sharey=True)
plt.suptitle(
    f"Bootstrapped Performance Distribution ({len(df_results) // 3} Iterations)",
    fontsize=16,
    y=1.03
)

for i, metric in enumerate(METRICS_TO_PLOT):
    ax = axes[i]
    
    # Create the box plot for the current metric
    sns.boxplot(
        data=df_results,
        x='Classifier',
        y=metric,
        hue='Dataset',
        ax=ax,
        palette="tab10",
        showmeans=True,
        meanline=True,
        medianprops={'color': 'red', 'linewidth': 2},
        meanprops={'marker': 'o', 'markerfacecolor': 'white', 'markeredgecolor': 'blue', 'markersize': 8},
    )
    
    # Set labels and titles
    ax.set_title(f'Median {metric} Distribution')
    ax.set_xlabel('Classifier Model')
    ax.set_ylabel(metric)
    ax.set_ylim(y_min, y_max)
    
    # Place the legend only on the first plot
    if i == 0:
        ax.legend(title='Dataset', loc='lower right')
    else:
        ax.get_legend().remove()
        
    ax.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout(rect=[0, 0, 1, 0.98]) # Adjust layout for suptitle
plt.show()
